name: manta_dart
version: 0.0.3
description: Manta Protocol implementation for Dart
author: Appia Systems Limited
homepage: http://appia.co
documentation: https://appiapay.github.io/manta-python
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  mqtt_client: ^10.10.0
  decimal: ^3.2.4
  uuid: ^4.5.1
  json_annotation: ">=2.0.0"
  logging: ^1.0.0
  pointycastle: ^3.6.1
  rsa_pkcs: ^2.1.0
  async: ^2.2.0

  meta: any
  asn1lib: any
dev_dependencies:
  test: ^1.3.4
  build_runner: ^2.6.0
  json_serializable: ">=2.0.0"
  mockito: ^5.5.0
